# Generated by Django 5.2.1 on 2025-06-04 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="formato: XXX.XXX.XXX-XX",
                        max_length=14,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "telefone_principal",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone Principal",
                    ),
                ),
                (
                    "telefone_secundario",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone Secundário",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "endereco_rua",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Rua/Avenida",
                    ),
                ),
                (
                    "endereco_numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "endereco_complemento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "endereco_bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "endereco_cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "endereco_uf",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "endereco_cep",
                    models.CharField(
                        blank=True,
                        help_text="formato: XXXXX-XXX",
                        max_length=9,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais sobre o tutor",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Paciente"),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("CANINO", "Canino"),
                            ("FELINO", "Felino"),
                            ("AVE", "Ave"),
                            ("REPTIL", "Réptil"),
                            ("ROEDOR", "Roedor"),
                            ("LAGOMORFO", "Lagomorfo (Coelho)"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Espécie",
                    ),
                ),
                (
                    "raca",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Raça"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Macho"),
                            ("F", "Fêmea"),
                            ("MC", "Macho Castrado"),
                            ("FC", "Fêmea Castrada"),
                            ("IND", "Indefinido"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "microchip",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Microchip",
                    ),
                ),
                (
                    "cor_pelagem",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cor da Pelagem",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("OBITO", "Óbito"),
                            ("TRANSFERIDO", "Transferido"),
                            ("PERDIDO", "Perdido"),
                        ],
                        default="ATIVO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do paciente",
                        null=True,
                        upload_to="pacientes_fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "observacoes_clinicas",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações Clínicas Relevantes",
                    ),
                ),
                (
                    "alergias_conhecidas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alergias Conhecidas"
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        help_text="Tutor responsável pelo paciente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacientes",
                        to="clinic.tutor",
                        verbose_name="Tutor Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nome"],
            },
        ),
    ]
