# Generated by Django 5.2.1 on 2025-06-10 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_sintoma_consulta_sintomas_apresentados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observacoes_exame_fisico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes_clinicas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_olhos',
            field=models.TextField(blank=True, help_text='Ex: secreção, olho vermelho/esbranquiçado, déficit visual, blefaroespasmo, fotofobia.', null=True, verbose_name='Anamnese Olhos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_pele_anexos',
            field=models.TextField(blank=True, help_text='Ex: higiene, secreção, alopecia, prurido, lesões, descamação, parasitas, orelha.', null=True, verbose_name='Anamnese Pele e Anexos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_cardiovascular',
            field=models.TextField(blank=True, help_text='Ex: intolerância a exercícios, cansaço, síncope, cianose, tosse.', null=True, verbose_name='Anamnese Sist. Cardiovascular'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_digestorio',
            field=models.TextField(blank=True, help_text='Ex: apetite, vômito, diarreia.', null=True, verbose_name='Anamnese Sist. Digestório'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_locomotor',
            field=models.TextField(blank=True, help_text='Ex: claudicação, trauma, aumento de volume, marcha, impotência, exercícios.', null=True, verbose_name='Anamnese Sist. Locomotor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_neurologico',
            field=models.TextField(blank=True, help_text='Ex: convulsão, síncopes, déficits, deambulação, audição, olfato, propriocepção, manias, deglutição, latido/miado.', null=True, verbose_name='Anamnese Sist. Neurológico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_reprodutor',
            field=models.TextField(blank=True, help_text='Ex: secreção, cio, anticoncepcional, prenhez, filhotes, mamas, comportamento.', null=True, verbose_name='Anamnese Sist. Reprodutor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_respiratorio',
            field=models.TextField(blank=True, help_text='Ex: secreção, tosse, espirro, cianose, dispnéia, ruído.', null=True, verbose_name='Anamnese Sist. Respiratório'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese_sistema_urinario',
            field=models.TextField(blank=True, help_text='Ex: ingestão de água, aspecto/volume/frequência da urina, tenesmo, disúria.', null=True, verbose_name='Anamnese Sist. Urinário'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_linfonodos_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação de Linfonodos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_mucosas_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação de Mucosas'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_nivel_consciencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nível de Consciência'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_postura',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Postura e Comportamento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_pulso_ppm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulso (ppm)'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_olhos',
            field=models.TextField(blank=True, help_text='Avaliação com oftalmoscópio, reflexos pupilares, pressão intraocular (se aplicável), etc.', null=True, verbose_name='Ex. Físico Olhos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_ouvidos',
            field=models.TextField(blank=True, help_text='Otoscopia, presença de cerúmen, odor, sensibilidade, etc.', null=True, verbose_name='Ex. Físico Ouvidos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_pele_anexos',
            field=models.TextField(blank=True, help_text='Avaliação de pelagem, presença de lesões, ectoparasitas, otoscopia, etc.', null=True, verbose_name='Ex. Físico Pele e Anexos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_cardiovascular',
            field=models.TextField(blank=True, null=True, verbose_name='Ex. Físico Sist. Cardiovascular'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_digestorio',
            field=models.TextField(blank=True, help_text='Avaliação de cavidade oral, abdômen (palpação, auscultação), etc.', null=True, verbose_name='Ex. Físico Sist. Digestório'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_locomotor',
            field=models.TextField(blank=True, help_text='Avaliação de claudicação, amplitude de movimento, dor articular/muscular, crepitação, etc.', null=True, verbose_name='Ex. Físico Sist. Locomotor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_neurologico',
            field=models.TextField(blank=True, help_text='Avaliação de estado mental, pares cranianos, reflexos espinhais, sensibilidade, coordenação, etc.', null=True, verbose_name='Ex. Físico Sist. Neurológico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_reprodutor',
            field=models.TextField(blank=True, help_text='Avaliação de testículos, próstata, vulva, vagina, glândulas mamárias, etc.', null=True, verbose_name='Ex. Físico Sist. Reprodutor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_respiratorio',
            field=models.TextField(blank=True, null=True, verbose_name='Ex. Físico Sist. Respiratório'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examefisico_sistema_urinario',
            field=models.TextField(blank=True, help_text='Palpação de rins, bexiga, avaliação de genitália externa, etc.', null=True, verbose_name='Ex. Físico Sist. Urinário'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes_exame_fisico_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Observações do Exame Físico Geral'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alimentacao_detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Alimentação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ambiente_onde_vive',
            field=models.TextField(blank=True, null=True, verbose_name='Ambiente em que Vive (detalhes)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirurgias_anteriores',
            field=models.TextField(blank=True, null=True, verbose_name='Cirurgias Anteriores'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contactantes_outros_animais',
            field=models.TextField(blank=True, null=True, verbose_name='Contactantes e Ambiente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='doencas_pregressas',
            field=models.TextField(blank=True, null=True, verbose_name='Doenças Pregressas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historico_vacinacao',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Vacinação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historico_vermifugacao',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Vermifugação'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes_clinicas_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Observações Clínicas Relevantes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procedência'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Atendimento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_proximo_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Próximo Retorno/Reavaliação'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='escore_condicao_corporal',
            field=models.CharField(blank=True, help_text='Ex: Caquético, Magro, Ideal, Sobrepeso, Obeso ou Escala 1-9', max_length=50, null=True, verbose_name='Escore de Condição Corporal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='exames_complementares_solicitados',
            field=models.TextField(blank=True, null=True, verbose_name='Exames Complementares Solicitados/Realizados e Resultados'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hidratacao_status',
            field=models.CharField(blank=True, help_text='Ex: Normohidratado, Desidratado (Leve, Moderado, Grave), Hiperhidratado', max_length=100, null=True, verbose_name='Status de Hidratação'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='historico_doenca_atual',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico da Doença Atual (evolução, tratamentos prévios)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='instrucoes_para_tutor',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções para o Tutor e Orientações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='queixa_principal_tutor',
            field=models.TextField(blank=True, null=True, verbose_name='Queixa Principal (relato do tutor)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sintomas_apresentados',
            field=models.ManyToManyField(blank=True, related_name='consultas_com_sintoma', to='clinic.sintoma', verbose_name='Sintomas Apresentados'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='suspeitas_diagnosticas',
            field=models.TextField(blank=True, null=True, verbose_name='Suspeita(s) Diagnóstica(s) / Diagnósticos Diferenciais'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('ROTINA', 'Rotina/Check-up'), ('EMERGENCIA', 'Emergência'), ('VACINACAO', 'Vacinação'), ('CIRURGIA', 'Cirurgia/Procedimento'), ('POS_CIRURGICO', 'Pós-Cirúrgico'), ('RETORNO', 'Retorno'), ('OUTRO', 'Outro')], default='ROTINA', max_length=20, verbose_name='Tipo de Consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamento_prescrito',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamento Prescrito (Medicamentos, doses, frequência)'),
        ),
    ]
