# Generated by Django 5.2.1 on 2025-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_consulta_observacoes_exame_fisico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Doença')),
                ('descricao', models.TextField(blank=True, help_text='Descrição técnica, etiologia, informações gerais sobre a doença.', null=True)),
                ('sintomas_associados', models.ManyToManyField(blank=True, to='clinic.sintoma', verbose_name='Sintomas Típicos Associados')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
                'ordering': ['nome'],
            },
        ),
    ]
