# Generated by Django 5.2.1 on 2025-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_doenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='diagnostico_definitivo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='suspeitas_diagnosticas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnosticos_definitivos',
            field=models.ManyToManyField(blank=True, related_name='consultas_com_diagnostico_definitivo', to='clinic.doenca', verbose_name='Diagnósticos Definitivos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnosticos_suspeitos',
            field=models.ManyToManyField(blank=True, related_name='consultas_com_suspeita', to='clinic.doenca', verbose_name='Suspeitas Diagnósticas'),
        ),
    ]
