# Generated by Django 5.2.7 on 2025-10-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_consulta_diagnostico_definitivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='microchip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Microchip'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(db_index=True, help_text='formato: XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nome'], name='paciente_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['microchip'], name='paciente_microchip_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tutor', 'nome'], name='paciente_tutor_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['cpf'], name='tutor_cpf_idx'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['email'], name='tutor_email_idx'),
        ),
    ]
